version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passwort
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  postgres:
