import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Moview</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-14 grid rounded-lg py-4 shadow-md">
        <h1 className="text-center text-4xl font-bold text-slate-900">
          Your friendly neighbourhood movie platform
        </h1>
      </div>

      <div className="mb-4 rounded-lg bg-slate-100 p-4 shadow-md">
        <p className="text-center text-xl  font-semibold text-primary-500">
          Your personal movie tickbox, rating list and review collection. Share
          your cultur in movies with friends and others.
        </p>
      </div>

      <div className="my-14 grid grid-cols-1">
        <button className="rounded-xl bg-primary-600 px-4 py-4 font-bold text-white">
          Get Started - completely free!
        </button>
      </div>

      <div>
        <p className=" text-xl font-bold text-primary-500">
          Moview satisfies all needs of a movie nerd:
        </p>

        <ul className="grid grid-cols-1 gap-4  text-primary-500 md:grid-cols-2">
          <li className="rounded-lg bg-mygray-100 p-4  font-bold  shadow-lg">
            <h2 className="text-xl text-primary-600">
              View Imdb&apos;s Best Rated!
            </h2>
            <p className="pl-2 pt-2 text-lg leading-6">
              Moview tracks the Top 250 movies listed in the official imdb web
              site so you know what is a must watch.
            </p>
          </li>
          <li className="rounded-lg  bg-mygray-100 p-4 font-bold shadow-lg">
            <h2 className="text-xl text-primary-600">
              Keep a list of your watched movies
            </h2>
            <p className="pl-2  pt-2 text-lg leading-6">
              Save the movies you have watched and share your impressive
              collection with others.
            </p>
          </li>
          <li className="rounded-lg bg-mygray-100 p-4 font-bold shadow-lg">
            <h2 className="text-xl text-primary-600">Rate and Review movies</h2>
            <p className="pl-2 pt-2 text-lg leading-6">
              Not only tick and rate movies, but review them as you were a
              professional critique a&apos;la cinemastrikesback
            </p>
          </li>
          <li className="rounded-lg bg-mygray-100 p-4 font-bold shadow-lg">
            <h2 className="text-xl text-primary-600">
              Keep an eye of what your fellas see and rate
            </h2>
            <p className="pl-2 pt-2 text-lg leading-6">
              See what you buddys watched and how they rate it, educate them why
              they are wrong and start the arguing!
            </p>
          </li>
        </ul>
      </div>
    </>
  );
};

export default Home;
